### ISSUE TITLE
Test Drive Unlimited hack

### ISSUE THREAD

**Issue by xTMODx** [LunaMoo/PPSSPP_workarounds#2]
Hi could you please add a hack for the european version of Test Drive Unlimited ULES-00637 or can i use the same code as the one for ULUS-10249?
```
_S ULUS-10249
_G Test Drive Unlimited
_C0 Remove slow and ugly effect
//This patches stuff on boot, aka requires restarting emulation/starting the game with cheat activated
_L 0xE0020406 0x002DC218
_L 0x202DC218 0x00003021
_L 0x202DC21C 0x00000000
_C0 Remove slow and ugly effect [Disable]
_L 0x202DC218 0x3C060406
_L 0x202DC21C 0x34C60002
```

**Comment by TAbdiukov** [comment]
The porting usually can be done as the following
1. Find some byte pattern covering the patch
2. Find the same pattern in the other ISO. With a good chance, it will work
3. Wrap things up into a .db and you have a working hack

**Comment by TAbdiukov** [comment]
@xTMODx here ya go

https://raw.githubusercontent.com/TAbdiukov/PPSSPP-patches/master/hacks_TDU_ULES00637.ini.db

```
_S ULES00637
_G Test Drive Unlimited [EUR]
// * Original ULUS patch by LunaMoo,
// https://github.com/LunaMoo/PPSSPP_workarounds/
// * Inspired by https://github.com/LunaMoo/PPSSPP_workarounds/issues/2
//
//
_C0 Remove stupid GBA-like pixelisation
//This patches stuff on boot, aka requires restarting emulation/starting the game with cheat activated
_L 0xE0020406 0x002DC288
_L 0x202DC288 0x00003021
_L 0x202DC28C 0x00000000
//
_C0 Remove stupid GBA-like pixelisation [Disable]
_L 0x202DC288 0x3C060406
_L 0x202DC28C 0x34C60002
//
```

Only needed to add +0x70 ! Too easy

**Comment by xTMODx** [comment]
Hey @TAbdiukov thanks for the patch :) will check it out later and close the issue when it is working

**Comment by xTMODx** [comment]
Sorry it is a bit late but i can confirm and close now because it works, thank you @TAbdiukov

**Comment by daltocybart** [comment]
Let's see, you say that it is easy but I do not understand how In what part of the code do I add 0x70?
@xTMODx 😆💯

**Comment by daltocybart** [comment]
The message was for the other TAbdiukov
, An apology but by the way, explain to me where I add the 0x70 in the Spanish psp TDU Code?

**Comment by TAbdiukov** [comment]
> The message was for the other TAbdiukov

No worries! I looked at the opcodes in the area that LunaMoo patches, and looked at what LunaMoo changes. Then I looked at the EUR version code, and the same opcodes were just close by. I then tried to apply the same patch and it worked

Actually since then I patched a few other games, and because across different regions, there are minimal changes, when the code is compiled, the addresses tend to be at the 'nearby' positions for everything. :)

**Comment by daltocybart** [comment]
I apologize for not knowing about it. For the patch of the European version of the TDU, psp. What am I supposed to do, do I have to change a number or something in the code? @TAbdiukov 💯😆

**Comment by daltocybart** [comment]
Tabdiukov, you are a Genius. I tried the code by activating it when I entered the game, Then, I took out the emulator and restart it again. I can say that it works the same as the English version. Thanks for creating the codes for the European version of TDU psp.

**Comment by TAbdiukov** [comment]
Naah, I'm just a common idiot :joy: @daltocybart

**Comment by daltocybart** [comment]
in fact I consider you one of the best people to contribute something of the TDU psp for me and all those who enjoy the game. including you

**Comment by daltocybart** [comment]
It is more in the American version of the TDU psp. When you go to the dealership you will find an open door Bug in the Corvette C1. Could it be that the game was prepared to use the internal camera of the game?
